CREATE DATABASE PETAPPS;
USE PETAPPS;
CREATE TABLE ESPECIE (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    ESTATUS BOOLEAN,
    PRIMARY KEY (ID)

)
INSERT INTO ESPECIE(NOMBRE, ESTATUS) VALUES('PERRO',1);
INSERT INTO ESPECIE(NOMBRE, ESTATUS) VALUES('GATO',1);
INSERT INTO ESPECIE(NOMBRE, ESTATUS) VALUES('CONEJO',0);